version: "2.1"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin #base image
    container_name: jellyfin #name of container
    hostname: jellyfin #name of virtual pc on network
    networks: #custom networks
      - webserver
    ports:
      - 8096:8096 #webos has problems with le certificates, using ports instead of reverse proxy
    environment: #environment variables
      - PUID=1001 #run the program as this user
      - PGID=1001 #group permissions for the program
      - TZ=Asia/Kolkata #timezone
    volumes: #persistent storage [source_on_host:destination_in_container]
      - ./jellyfin-config:/config #configration files
      - /home/bv/media:/media #media folder (not read-only since jellyfin writes metadata)
    restart: unless-stopped #automatically restart 

networks: #define custom networks
   webserver:
     external: true #use predefined network
